version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@feliperamos"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
    groups:
      # Group React-related dependencies
      react:
        patterns:
          - "react*"
          - "@types/react*"
      # Group testing dependencies
      testing:
        patterns:
          - "@testing-library/*"
          - "jest*"
          - "@types/jest"
      # Group ESLint dependencies
      linting:
        patterns:
          - "eslint*"
          - "@eslint/*"
      # Group TypeScript dependencies
      typescript:
        patterns:
          - "typescript"
          - "@types/*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
    open-pull-requests-limit: 5
    reviewers:
      - "@feliperamos"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
